In [3]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(a)
a=np.arange(9).reshape(3,3)
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
i=0
b=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(b)
b[b%2!=0] = -1
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [30]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(x)
print(y)
print(np.where(x>y))
print(np.where(x==y))

[21 64 86 22 74 55 81 79 90 89]
[21  7  3 45 10 29 55  4 37 18]
(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [29]:
data=np.arange(100).reshape(5,-1)
print(arr)
subset = data[:, 0:4]
print(subset)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [45]:
import random
arr=[]
arr=np.random.randint(30,40,10)
print(arr)

[35 33 34 38 34 36 37 32 34 35]


In [64]:
a= [[1, 2, 3], [4, 5, 6], [7, 8, 10]]
b = [[7, 8, 10] ,[4, 5, 6], [1, 2, 3]]
c = np.add(a,b)
d = np.dot(a,b)
e = np.subtract(a,b)
f=np.sum(a)
g=np.sum(b, axis=0)
h=np.sum(c, axis=1)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(np.sort(c))
print(e.transpose())

[[1, 2, 3], [4, 5, 6], [7, 8, 10]]
[[7, 8, 10], [4, 5, 6], [1, 2, 3]]
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
46
[12 15 19]
[31 30 31]
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
